import './globals.css'
import { Montserrat, Lobster } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'], variable:'--font-mont'})
const lobster = Lobster({ subsets: ['latin'],weight:'400', variable:'--font-lob'})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${lobster.variable} bg-light w-full min-h-screen`}>{children}</body>
    </html>
  )
}
