import NavBar from '@/components/NavBar'
import './globals.css'
import { Montserrat, Lobster } from 'next/font/google'
import Footer from '@/components/Footer'

const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-mont' })
const lobster = Lobster({ subsets: ['latin'], weight: '400', variable: '--font-lob' })

export const metadata = {
  title: 'Portifólio Rodrigo Menezes',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${lobster.variable} bg-light dark:bg-dark w-full min-h-screen`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
